- name: Check Exists apache2.4
  stat: path={{INSTALL_DIR}}/apache2.4.29/bin
  register: st
  
- name: create folder apache2
  file: path={{item}} state=directory 
  with_items:
     - "/tmp/apache2.4"
     - "{{HTTP_LOGS}}" 
  when: not st.stat.exists
    
- name: downloads httpd tar gz file
  get_url: url={{item}} dest=/tmp/apache2.4/
  when: not st.stat.exists
  with_items : 
      - "{{HTTPD_DOWNLOADS}}"
      - "{{APR_DOWNLOADS}}"
      - "{{APR_UTIL_DOWNLOADS}}"
 
- name: extract all archives 
  unarchive: src={{item}}  copy=no dest=/tmp/apache2.4/
  when: not st.stat.exists
  with_items:
     - "/tmp/apache2.4/apr-1.6.3.tar.gz"
     - "/tmp/apache2.4/apr-util-1.6.1.tar.gz"
     - "/tmp/apache2.4/httpd-2.4.29.tar.gz"
     
- name: delete all tar.gz files
  command: rm {{item}}
  args:
   chdir: /tmp/apache2.4 
  with_items:
     - "apr-1.6.3.tar.gz"
     - "apr-util-1.6.1.tar.gz"
     - "httpd-2.4.29.tar.gz"
  when: not st.stat.exists
   
- name : move APR-UTIL
  command: mv /tmp/apache2.4/apr-util-1.6.1 /tmp/apache2.4/httpd-{{HTTPD_VERSION}}/srclib/apr-util 
  when: not st.stat.exists
  
- name : move APR
  command: mv /tmp/apache2.4/apr-1.6.3 /tmp/apache2.4/httpd-{{HTTPD_VERSION}}/srclib/apr
  when: not st.stat.exists
  
- yum: name=gcc state=present 
- yum: name=pcre state=present
- yum: name=pcre-devel state=present
- yum: name=openssl-devel  state=present
- yum: name=expat-devel state=present
- yum: name=libxml2-devel state=present
   
- name: Configure httpd
  command: ./configure --enable-ssl --enable-so --enable-mods-shared=all --with-included-apr --prefix={{INSTALL_DIR}}/apache2.4.29
  args:
    chdir: /tmp/apache2.4/httpd-{{HTTPD_VERSION}}
  when: not st.stat.exists
  
- name: make httpd
  command: make 
  args:
    chdir: /tmp/apache2.4/httpd-{{HTTPD_VERSION}}
  when: not st.stat.exists
  
- name: make httpd
  command: make install
  args:
    chdir: /tmp/apache2.4/httpd-{{HTTPD_VERSION}}
  when: not st.stat.exists
   
- name: configure httpd.conf and modsecurity.conf 
  template: src={{item}} dest={{INSTALL_DIR}}/apache2.4.29/conf/
  with_items:
    - "httpd.conf"
    - "modsecurity.conf"
  when: not st.stat.exists
  
- name: create certificat folder ssl
  file: path={{INSTALL_DIR}}/apache2.4.29/certificats state=directory  
  when: not st.stat.exists
  
- name: downloads mod_security modules
  get_url: url={{URL_DOWNLOADS_MOD_SEC}} dest=/tmp/apache2.4/
  when: not st.stat.exists
  
- name: extract mod_security.tar.gz file 
  unarchive: src={{item}}  copy=no dest=/tmp/apache2.4/
  when: not st.stat.exists
  with_fileglob:
     - "/tmp/apache2.4/*"
     
- name: configure install resource modsecurity 
  command: ./configure --with-apxs={{INSTALL_DIR}}/apache2.4.29/bin/apxs --with-apr={{INSTALL_DIR}}/apache2.4.29/bin/apr-1-config  --with-apu={{INSTALL_DIR}}/apache2.4.29/bin/apu-1-config
  
  args:
    chdir: /tmp/apache2.4/modsecurity-{{MODSEC_VERSION}}
  when: not st.stat.exists

- name: configure install resource modsecurity 
  command: make 
  args:
    chdir: /tmp/apache2.4/modsecurity-{{MODSEC_VERSION}}
  when: not st.stat.exists

- name: configure install resource modsecurity 
  command: make install
  args:
    chdir: /tmp/apache2.4/modsecurity-{{MODSEC_VERSION}}
  when: not st.stat.exists
  
       
- command: firewall-cmd --zone=public --add-port=443/tcp --permanent
- command: firewall-cmd --zone=public --add-service=https --permanent
- command: firewall-cmd --reload
  
